# Site settings
name: Siddhant Keshkar
email: siddhantkeshkar@gmail.com
#canonical_url: https://siddhantkeshkar.com
keywords: "Software Engineer, Java, Python, C++, Machine Learning, Startups"
skills: "C.S. Grad. Student at CU Boulder(Graduating May 2021)"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/siddhant-keshkar/
  - title: instagram
    url: https://www.instagram.com/dslr_bina_photography/
  - title: twitter
    url: https://twitter.com/SiddhantKeshkar

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1EB6EE
  primary-rgb: "30, 182, 238"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
